import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BellRing, Check, Loader2, MessageSquare, Plus, Trash2, Languages } from 'lucide-react'
import clsx from 'clsx'
import { api, qs } from '../lib/api'
import { useAuth } from '../lib/auth'
import { useI18n } from '../lib/i18n'
import { useToast } from '../lib/toast'
import { Card, EmptyState, ErrorState, Field, Modal, PageHeader, Pagination, Segmented, timeAgo } from '../components/ui'

const SEV = { critical: 'bg-red-100 text-red-700 border-red-200', warning: 'bg-amber-100 text-amber-800 border-amber-200', info: 'bg-sky-100 text-sky-800 border-sky-200' }

export default function Alerts() {
  const { isClinical, isDistrictPlus } = useAuth()
  const { t, lang } = useI18n()
  const toast = useToast()
  const qc = useQueryClient()
  const [sev, setSev] = useState('')
  const [page, setPage] = useState(1)
  const [open, setOpen] = useState(false)
  const [preview, setPreview] = useState(null)
  const q = useQuery({ queryKey: ['alerts', sev, page, lang], queryFn: () => api(`/api/v1/alerts${qs({ severity: sev, page, page_size: 15 })}`), placeholderData: (p) => p })
  const inv = () => qc.invalidateQueries({ queryKey: ['alerts'] })
  const ack = useMutation({
    mutationFn: (id) => api(`/api/v1/alerts/${id}/ack`, { method: 'POST', body: {} }),
    onMutate: async (id) => { const key = ['alerts', sev, page, lang]; const prev = qc.getQueryData(key); qc.setQueryData(key, (d) => d && { ...d, items: d.items.map((a) => a.id === id ? { ...a, acked: 1, acks: a.acks + 1 } : a) }); return { prev, key } },
    onError: (e, _id, ctx) => { qc.setQueryData(ctx.key, ctx.prev); toast.error(e.message) }, onSettled: inv,
  })
  const del = useMutation({ mutationFn: (id) => api(`/api/v1/alerts/${id}`, { method: 'DELETE' }), onSuccess: () => { toast.success('Alert withdrawn'); inv() } })
  const loadPreview = async (a) => { const r = await api(`/api/v1/alerts/${a.id}/preview`); setPreview({ a, ...r.preview }) }
  if (q.isError) return <ErrorState error={q.error} retry={q.refetch} />
  return (
    <div className="space-y-4">
      <PageHeader title={t('Alerts')} subtitle="Multilingual advisories — auto-generated by triage/lab/cluster events or issued by officers" actions={<><Segmented value={sev} onChange={(v) => { setSev(v); setPage(1) }} options={[{ value: '', label: 'All' }, { value: 'critical', label: 'Critical' }, { value: 'warning', label: 'Warning' }, { value: 'info', label: 'Info' }]} />{isClinical && <button onClick={() => setOpen(true)} className="btn-primary"><Plus className="h-4 w-4" />Issue advisory</button>}</>} />
      <Card padded={false}>
        {q.isLoading ? <div className="p-4 space-y-3">{[...Array(6)].map((_, i) => <div key={i} className="skeleton h-16" />)}</div> : !q.data.items.length ? <EmptyState icon={BellRing} title="No alerts" detail="Advisories targeted to your village, taluka, district or statewide appear here." /> : (
          <ul className="divide-y divide-slate-100">{q.data.items.map((a) => (
            <li key={a.id} className={clsx('flex gap-4 px-5 py-4', !a.acked && a.severity === 'critical' && 'bg-red-50/40')}>
              <span className={clsx('mt-1 h-fit shrink-0 rounded-lg border px-2 py-0.5 text-[10px] font-bold uppercase', SEV[a.severity])}>{a.severity}</span>
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2"><span className="font-semibold text-slate-900">{a.title}</span><span className="badge bg-slate-100 text-slate-600">{a.kind.replace(/_/g, ' ')}</span></div>
                <p className="mt-1 text-sm text-slate-700">{a.message}</p>
                <div className="mt-1.5 flex flex-wrap items-center gap-x-3 gap-y-1 text-[11px] text-slate-500">
                  <span>📍 {a.area}</span><span>{timeAgo(a.created_at)} · {a.created_by_name}</span><span>{a.channels.join(' · ')}</span><span>{a.acks} ack</span>
                  {a.case_id && <Link to={`/cases/${a.case_id}`} className="font-mono text-forest-700 hover:underline">{a.case_id}</Link>}
                  <button onClick={() => loadPreview(a)} className="flex items-center gap-1 text-forest-700 hover:underline"><Languages className="h-3 w-3" />en · मर · हि</button>
                </div>
              </div>
              <div className="flex shrink-0 flex-col items-end gap-1">
                <button onClick={() => !a.acked && ack.mutate(a.id)} className={clsx('btn !py-1 text-xs', a.acked ? 'bg-forest-50 text-forest-700' : 'btn-secondary')} disabled={!!a.acked}><Check className="h-3.5 w-3.5" />{a.acked ? 'Acknowledged' : 'Acknowledge'}</button>
                {isDistrictPlus && <button onClick={() => del.mutate(a.id)} className="btn-ghost !p-1 text-slate-400 hover:!text-red-600"><Trash2 className="h-3.5 w-3.5" /></button>}
              </div>
            </li>
          ))}</ul>
        )}
        {q.data && <Pagination page={q.data.page} pages={q.data.pages} total={q.data.total} onPage={setPage} />}
      </Card>
      <Modal open={!!preview} onClose={() => setPreview(null)} title="Channel renderings" wide>
        {preview && <div className="grid gap-3 sm:grid-cols-3">{['en', 'mr', 'hi'].map((l) => <div key={l} className="rounded-xl border border-slate-200 p-3 text-sm"><div className="mb-2 text-xs font-bold uppercase text-slate-500">{{ en: 'English', mr: 'मराठी', hi: 'हिंदी' }[l]}</div><div className="mb-2"><div className="text-[10px] font-semibold text-slate-400">SMS ({preview[l].sms.length}/160)</div><div className="rounded-lg bg-slate-50 p-2 text-xs">{preview[l].sms}</div></div><div className="mb-2"><div className="text-[10px] font-semibold text-slate-400">WhatsApp</div><div className="whitespace-pre-wrap rounded-lg bg-green-50 p-2 text-xs">{preview[l].whatsapp}</div></div><div><div className="text-[10px] font-semibold text-slate-400">IVR script</div><div className="rounded-lg bg-amber-50 p-2 text-xs">🔊 {preview[l].ivr_script}</div></div></div>)}</div>}
      </Modal>
      <IssueModal open={open} onClose={() => setOpen(false)} onDone={inv} />
    </div>
  )
}

function IssueModal({ open, onClose, onDone }) {
  const toast = useToast()
  const { user } = useAuth()
  const gaz = useQuery({ queryKey: ['gazetteer'], queryFn: () => api('/api/v1/geo/gazetteer'), staleTime: Infinity, enabled: open })
  const [f, setF] = useState({ title: '', message_en: '', message_mr: '', message_hi: '', severity: 'warning', kind: 'advisory', district_code: user.district_code || '', taluka_code: user.taluka_code || '', village_code: '', channels: ['app', 'sms', 'whatsapp', 'ivr'], expires_days: 7 })
  const m = useMutation({ mutationFn: () => api('/api/v1/alerts', { method: 'POST', body: f }), onSuccess: () => { toast.success('Advisory issued', 'Pushed to connected dashboards via SSE'); onDone(); onClose() }, onError: (e) => toast.error(e.message) })
  const toggle = (c) => setF({ ...f, channels: f.channels.includes(c) ? f.channels.filter((x) => x !== c) : [...f.channels, c] })
  return (
    <Modal open={open} onClose={onClose} title="Issue advisory" wide footer={<><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={!f.title || !f.message_en || m.isPending} onClick={() => m.mutate()}>{m.isPending && <Loader2 className="h-4 w-4 animate-spin" />}<MessageSquare className="h-4 w-4" />Issue</button></>}>
      <div className="grid gap-3 sm:grid-cols-2">
        <Field label="Title" required><input className="input" value={f.title} onChange={(e) => setF({ ...f, title: e.target.value })} /></Field>
        <Field label="Severity"><select className="input" value={f.severity} onChange={(e) => setF({ ...f, severity: e.target.value })}><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></select></Field>
        <div className="sm:col-span-2"><Field label="Message (English)" required><textarea className="input" rows={2} value={f.message_en} onChange={(e) => setF({ ...f, message_en: e.target.value })} /></Field></div>
        <Field label="संदेश (मराठी)" hint="Falls back to English if empty"><textarea className="input" rows={2} value={f.message_mr} onChange={(e) => setF({ ...f, message_mr: e.target.value })} /></Field>
        <Field label="संदेश (हिंदी)"><textarea className="input" rows={2} value={f.message_hi} onChange={(e) => setF({ ...f, message_hi: e.target.value })} /></Field>
        <Field label="District"><select className="input" value={f.district_code} disabled={!!user.district_code} onChange={(e) => setF({ ...f, district_code: e.target.value, taluka_code: '', village_code: '' })}><option value="">Statewide</option>{gaz.data?.districts.map((d) => <option key={d.code} value={d.code}>{d.name}</option>)}</select></Field>
        <Field label="Taluka"><select className="input" value={f.taluka_code} disabled={!!user.taluka_code} onChange={(e) => setF({ ...f, taluka_code: e.target.value, village_code: '' })}><option value="">Whole district</option>{gaz.data?.talukas.filter((t) => t.district_code === f.district_code).map((t) => <option key={t.code} value={t.code}>{t.name}</option>)}</select></Field>
        <Field label="Village"><select className="input" value={f.village_code} onChange={(e) => setF({ ...f, village_code: e.target.value })}><option value="">Whole taluka</option>{gaz.data?.villages.filter((v) => v.taluka_code === f.taluka_code).map((v) => <option key={v.code} value={v.code}>{v.name}</option>)}</select></Field>
        <Field label="Expires in (days)"><input type="number" className="input" value={f.expires_days} onChange={(e) => setF({ ...f, expires_days: +e.target.value })} /></Field>
        <div className="sm:col-span-2"><span className="label">Channels</span><div className="flex flex-wrap gap-2">{['app', 'sms', 'whatsapp', 'ivr'].map((c) => <button key={c} type="button" onClick={() => toggle(c)} className={clsx('rounded-full border px-3 py-1 text-xs uppercase', f.channels.includes(c) ? 'border-forest-700 bg-forest-800 text-white' : 'border-slate-200')}>{c}</button>)}</div></div>
      </div>
    </Modal>
  )
}
